language: python
python:
  - "2.7"
install:
  - pip install flake8 docutils
  - sudo apt-get install solr-jetty openjdk-6-jdk
script:
  - flake8 odgovlt.py
  - rst2html.py --strict README.rst /dev/null
  - flake8 tests
  - make test
  
